site:
  title: Style test
  start_page: next@style-test:en:introduction.adoc

content:
  sources:
    - url: ./
      branches: [main]
      start_paths: [docs/next]

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  #supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build-def/site
