site:
  title: Style test
  start_page: next@style-test:en:introduction.adoc

content:
  sources:
    - url: ./
      branches: [main]
      start_paths: [docs/next]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files.new-style

asciidoc:
  attributes:
    kw-build-type: 'product' # 'community' or 'product'
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build-ns/site
