site:
  title: Kubewarden documentation
  start_page: 1.18@policy-manager:en:introduction.adoc

content:
  sources:
    - url: https://github.com/rancher/kubewarden-product-docs.git
      branches: [main]
      start_paths: [docs/next, docs/version-*]

ui:
  bundle:
    url: tmp/sp
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    kw-build-type: 'community'
    kw-rancher-product-name: 'Rancher Policy Engine'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
