site:
  title: Style test
  start_page: next@style-test:en:introduction.adoc

content:
  sources:
    - url: https://github.com/jhkrug/style-test.git
      branches: [main]
      start_paths: [docs/next]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    kw-build-type: 'community'
    kw-rancher-product-name: 'Rancher Policy Engine'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
