= Links

== Links and pass throughs

Example from JM:

`pass:[https://releases.rancher.com/harvester/{version}/version.yaml]`

This is just a link:

https://blah-fubar.org

This is a link with name:

https://blah-fubar.org[Blah Fubar]

This is a link with a pass through:

pass:[https://example.com]

This a monospace link:

`https://blah-fubar.org`

This is a monospace link with a name:

https://blah-fubar.org[`Blah Fubar`]

A monospace link that is not linked:

`pass:[https://blah-fubar.org]`

A link that is escaped with a single backslash:

\https://blah-fubar.org

A monospaced link that is escaped with a single backslash:

`\https://blah-fubar.org`

A link escaped with `[subs=-macros]`:

[subs=-macros]
https://blah-fubar.org

A monospace link escaped with `[subs=-macros]`:

[subs=-macros]
`https://blah-fubar.org`

A link escaped with `[subs=-macros]` and additional surrounding text:

[subs=-macros]
Additional https://blah-fubar.org surrounding text.

A monospace link escaped with `[subs=-macros]` and additional surrounding text:

[subs=-macros]
Additional `https://blah-fubar.org` surrounding text.

The literal monospace method:

`+https://blah-fubar.org+`

== URLs and URL macros

URLs and URL macros are preferred. Use link macros only where necessary
(relative links to pdf or html, to adoc, use an xref).

This is a URL https://documentation.suse.com.

This is a URL macro https://documentation.suse.com[].

This is a URL macro with link text https://documentation.suse.com[SUSE docs].

As a link link:https://documentation.suse.com[].

As a link with link text link:https://documentation.suse.com[SUSE docs].

