:experimental:
= Tables

[#ref-table-1]
.The first table
|===
| Header 1 | Header 2 with a https://blah.com[link]

| Row 1, Col 1
| Row 1, Col 2

| Row 2, Col 1
| Row 2 with a https://blah.com[link], Col 2

| Row 3, Col 1
| Row 3, Col 2

| Row 4, Col 1
| Row 4, Col 2

| Row 5, Col 1
| Row 5, Col 2
|===

Next, a table with keyboard macros.

[#ref-table-2]
.The second table
|===
|Shortcut |Purpose

|kbd:[F11]
|Toggle fullscreen

|kbd:[Ctrl+T]
|Open a new tab

|kbd:[Ctrl+Shift+N]
|New incognito window

|kbd:[\ ]
|Used to escape characters

|kbd:[Ctrl+\]]
|Jump to keyword

|kbd:[Ctrl + +]
|Increase zoom
|===

And more

Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.

And more

Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.

And more

Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.

And more

Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.

And more

Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.

And more

Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.

== Referencing a table

Look at xref:#ref-table-1[] to the table at the top of the page.

Look at xref:#ref-table-2[] to the second table.

== More tables

.Good
[%header,cols="2,1,1"]
|===
| Animal | Legs | Can Fly?
| Dog | 4 | no
| Bird | 2 | yes
| Snake | 0 | no
|===

.Bad
[%header,cols="2,1,1"]
|===
| | Legs | Can Fly?
| Dog | 4 | no
| Bird | 2 | yes
| Snake | 0 | no
|===

== Complex example from Dmitri Popov

:trserver: Trento&nbsp;Server
:tragent: Trento&nbsp;Agent

.Compatibility matrix between {trserver} and {tragent}s
[cols="^2,^1,^1,^1,^1,^1,^1,^1,^1", options="header"]
|===
^|{tragent} 8+^|{trserver}|
|1.0 |1.1 |1.2 |2.0 |2.1 |2.2 |2.3 |2.4

|1.0 |[.green]#✓# | | | | | | |
|1.1 |[.green]#✓# |[.green]#✓# | | | | | |
|1.2 |[.green]#✓# |[.green]#✓# |[.green]#✓# | | | | |
|2.0 | | | |[.green]#✓# | | | |
|2.1 | | | |[.green]#✓# |[.green]#✓# | | |
|2.2 |[.blue]#🗶# | | |[.green]#✓# |[.green]#✓# |[.green]#✓# | |
|2.3 |[.red]#☒# | | |[.green]#✓# |[.green]#✓# |[.green]#✓# |[.green]#✓# |
|2.4 |[.red]#🗶# | | |[.green]#✔# |[.green]#🗹# |[.green]#✓# |[.green]#🎉# |[.green]#✓#
|===