name: Build and deploy PR
on:
  # Runs every hour.
  #schedule:
  #  - cron: "0 * * * *"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    #environment:
    #  name: github-pages
    #  url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install and build with Antora
        run: make rancher-dsc
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build-rancher-dsc/site
      - name: Push the static site content to gh-pages branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          mv build-rancher-dsc/site ../site-temp
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf node_modules tmp
          mkdir -p preview/pr
          mv ../site-temp/* preview/pr/.
          git add .
          git commit -m "Deploy to gh-pages branch"
          git push --force origin gh-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4