name: Delete PR preview

on:
  pull_request:
    types:
      - closed

concurrency: pr-close-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: PR closed
        run: |
          echo "pr-closed ${{ github.ref }}"