name: Deploy PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-pr-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4
      - name: Build
        run: |
          echo "pr-build ${{ github.ref }}"